### ISSUE TITLE
dont mean to be a dick but...

### ISSUE THREAD

**Issue by avtamat** [Blaumaus/le_chiffre#12]
recommending to rename the file?
recommending junk code? 

come on

**Comment by Blaumaus** [comment]
@avtamat, first of all, I did not recommend adding junk code, I said that it's one of the options that might help in some cases.
What's wrong with junk code and file renaming on your opinion?

**Comment by avtamat** [comment]
junk code means you have to have optimization disabled in the compiler, why would you EVER turn off optimization?

there is nothing wrong with file naming, not at all, i think i worded it wrong. but what does file renaming have to do with detection rates? hack.exe and school_homework.exe are gonna have the same detection rates.

**Comment by Blaumaus** [comment]
@avtamat, when I said "junk code" in the previous thread I actually meant making the cheats as unique as possible.
You should reimplement the cheat menu, hacks and such stuff in your way to make the cheat less detectable.

Also maybe I'm wrong, but I suppose if 10000 people run Le_Chiffre.exe with the same file hashes and one of them gets detected, all the people who ran the cheat also will get banned by VAC. Maybe I'm wrong, I'm not a 100% sure how VAC analyses cheats, but renaming the cheat and changing it's hash is a "must have".

**Comment by avtamat** [comment]
i'm just going to stop arguing. i strongly believe that renaming the file does nothing.

also, that's not junk code. i recommend you go into the readme and replace the junk code part with exactly what you said 

>You should reimplement the cheat menu, hacks and such stuff in your way to make the cheat less detectable. 

i think you worded it well.

again I'm not here to argue, I have nothing against you or your project (frankly i like it), but I think that what you said isn't the proper information to be giving out, but then again, I don't 100% know how vac works.

**Comment by Blaumaus** [comment]
done.

**Comment by Null69** [comment]
adding junk code with turned off optimization + building the cheat yourself will change the signature of the exe
i dont think it's a "bad" thing

**Comment by avtamat** [comment]
dont. turn. off. optimization.

**Comment by avtamat** [comment]
can't believe you'd be willingly shitting in your cheat so it can change the signature a little

**Comment by Null69** [comment]
sure, it's not a problem for me i dont have shitty computer tho and it wont increase its memory or cpu usage too much

**Comment by avtamat** [comment]
im convinced you have no idea what you're doing if you think that it's about having a shitty computer and that it's okay to disable optimization in your IDE and put thousands of lines of junk code to make it ""undetected"".
