### ISSUE TITLE
New update 1.21.2021

### ISSUE THREAD

**Issue by Null69** [Blaumaus/le_chiffre#13]

**Comment by Blaumaus** [comment]
@Null69 https://github.com/Blaumaus/le_chiffre/releases/tag/v1.0.4

**Comment by Blaumaus** [comment]
also i think offsets autoparser will come in the next release

**Comment by Null69** [comment]
> also i think offsets autoparser will come in the next release

What does that mean?, You'll integrate hazedumper in your source so everytime there's an update the cheat automatically scan and dump the latest offsets??
