### ISSUE TITLE
Does not work anymore

### ISSUE THREAD

**Issue by valoo22** [Blaumaus/le_chiffre#16]
Hi , your app Doesn't work anymore , probably because update this morning , it's possible to update your app ?
(BTW Good work thanks ^^ )

**Comment by Blaumaus** [comment]
@valoo22 https://github.com/Blaumaus/le_chiffre/releases/tag/v1.1.2

**Comment by valoo22** [comment]
Dude too fast you gotta fast ^^^
Thanks ^^
