### ISSUE TITLE
need new version

### ISSUE THREAD

**Issue by senseless1337** [Blaumaus/le_chiffre#18]
hey bro, send new version pls

**Comment by Nikos665** [comment]
I hope the hack will be updated soon,and yes, the author of this hack is the best

**Comment by Blaumaus** [comment]
@senseless1337, @Nikos665 done. 
Also a question for you guys: does the cheat version state detector works correctly for you (shows either LATEST or OUTDATED in cheat menu) or does it display an ERROR message?

**Comment by Null69** [comment]
> @senseless1337, @Nikos665 done.
> Also a question for you guys: does the cheat version state detector works correctly for you (shows either LATEST or OUTDATED in cheat menu) or does it display an ERROR message?

it says OUTDATED but doesn't matter for me cuz I update offsets regularly

**Comment by senseless1337** [comment]
> @senseless1337, @Nikos665 done.
> Also a question for you guys: does the cheat version state detector works correctly for you (shows either LATEST or OUTDATED in cheat menu) or does it display an ERROR message?

it says "OUTDATED"
