### ISSUE TITLE
can I have a settings to be changed before compiling the new source?

### ISSUE THREAD

**Issue by Null69** [Blaumaus/le_chiffre#19]
I got this error "LNK2001: unresolved external symbol main" in the new source code update

**Comment by Blaumaus** [comment]
@Null69 yes, I've changed the entry point from regular `main` function into `WinAPI WinMain`.

To fix this you have to either download the latest project settings from repository or fix this manually by setting linker /SUBSYSTEM setting to WINDOWS.

See details here: https://docs.microsoft.com/en-us/cpp/build/reference/subsystem-specify-subsystem?view=msvc-160

**Comment by Null69** [comment]
Thanks, when opening the .sln of any projects I downloaded, their settings are not getting applied to my Visual Studio I don't know why ;<
