### ISSUE TITLE
1.2.0 Dosnt work for me :/

### ISSUE THREAD

**Issue by razeNFR** [Blaumaus/le_chiffre#20]
I have been using your cheat for a long time but since version 1.2.0 the cheat does not work for me anymore. I tried to run before and after CS:GO, I tried to run in Admin, but nothing works.

**Comment by valoo22** [comment]
same , last update today or yesteday break the cheat , probably because memory has changed , go wait the new version

**Comment by Blaumaus** [comment]
@valoo22 @razeNFR https://github.com/Blaumaus/le_chiffre/releases/tag/v1.2.1
