### ISSUE TITLE
Hey ! Suggestion 🗡️ 

### ISSUE THREAD

**Issue by razeNFR** [Blaumaus/le_chiffre#22]
Hello ! 

First, very thank for all your job and i love your hack, but its possible to make a tutoriel for update memory offset of glow esp ? I wanna know how i can do this, i know its with cheat engine or something like that but i tried to search on the web and i cant find something.

**Comment by Blaumaus** [comment]
@razeNFR visit https://github.com/frk1/hazedumper, find the csgo.hpp there.
Copy & paste the `hazedumper namespace` into `Le_Chiffre/signatures.hpp`.
Compile the source code using the Visual Studio (with at least C++17 language standard selected). Profit.
