### ISSUE TITLE
Aim assist project

### ISSUE THREAD

**Issue by Mairou-tech** [Blaumaus/le_chiffre#23]
Question:

You wrote that you planned to do an Aim Assist, is that still a thing ?
If yes when do you plan to create it ?

Thanks

**Comment by Blaumaus** [comment]
@Mairou-tech yes I plan to add this somewhen, but now I don't have too much time to work on this project.
If you do know C++, you may try to add this feature by yourself. 
This project is always opened to pull requests and proposals.

**Comment by Mairou-tech** [comment]
Thanks for the awnser.

Well i do know C++ but i've never used it around CSGO cheats or so, then i might be not good enough to add this feature by myself. I might try some time anyway.
