### ISSUE TITLE
Environment configuration

### ISSUE THREAD

**Issue by AbrnYa** [Blaumaus/le_chiffre#26]
Hello author, I like your project very much, but...How can I configure the corresponding environment? My visual studio 2019 console has been reporting errors

**Comment by Blaumaus** [comment]
@AbrnYa, what errors did your console report?

**Comment by AbrnYa** [comment]
![image](https://user-images.githubusercontent.com/77602247/112802263-8d9f5d80-90a4-11eb-9dcb-1adb50bad4ea.png)

**Comment by Blaumaus** [comment]
@AbrnYa https://github.com/Blaumaus/le_chiffre/issues/19

**Comment by AbrnYa** [comment]
> @AbrnYa #19

You are wonderful. Thank you for your help

**Comment by Blaumaus** [comment]
you're welcome
