### ISSUE TITLE
Faceit

### ISSUE THREAD

**Issue by zxcyyyy** [Blaumaus/le_chiffre#29]
Hi just wanna ask if the program is safe to use in Faceit? I know there is risk using the program, but I just wanna know if it's as safe as the normal competitive matchmaking server. Thank you

**Comment by AbrnYa** [comment]
> 您好，我想问一下该程序在Faceit中是否可以安全使用？我知道使用该程序存在风险，但我只是想知道它是否像普通的竞争性配对服务器一样安全。谢谢

There are risks in using any third-party tools, which can not be avoided, but can be reduced by some methods.

**Comment by AbrnYa** [comment]
> 您好，我想问一下该程序在Faceit中是否可以安全使用？我知道使用该程序存在风险，但我只是想知道它是否像普通的竞争性配对服务器一样安全。谢谢

We can reduce the risk by encrypting the EXE file, modifying the hash and modifying the characteristics, making it unique

**Comment by zxcyyyy** [comment]
That is understood. Thank you
