### ISSUE TITLE
Need to be helped urgently

### ISSUE THREAD

**Issue by Namelerustunde** [Blaumaus/le_chiffre#33]
I open the game and open the cheat after it opens. When I want to activate the cheat by entering the game and pressing the F8 key, it kills the game and the game closes. Please help me , ty

**Comment by WhaleHK** [comment]
> I open the game and open the cheat after it opens. When I want to activate the cheat by entering the game and pressing the F8 key, it kills the game and the game closes. Please help me , ty

There was a small update in CS:GO which changed the offsets for Player Positions. Just got to wait for Chiffre to update.

**Comment by Blaumaus** [comment]
@Namelerustunde @WhaleHK https://github.com/Blaumaus/le_chiffre/releases/tag/v1.3.4
