### ISSUE TITLE
ALT+TAB BUG

### ISSUE THREAD

**Issue by WhaleHK** [Blaumaus/le_chiffre#36]
When you ALT+TAB with the cheats open, it sometimes bugs and stops working completely. You will have to close and reopen it. I think it's due to TriggerBot's keybind as LAlt. 

I'm not sure how you will be able to fix this, but it happens pretty often; I'd say around 10-25% of the time I ALT+TAB.

EDIT: 
- Has happened on the older versions of the cheat. 

A screenshot of the bug is attached.

![Capture](https://user-images.githubusercontent.com/82735148/116840856-410bde00-ab8c-11eb-9a93-b4343a8b1ea6.PNG)

**Comment by Blaumaus** [comment]
@WhaleHK you may try to press F1 to force the cheat rerender it's layout

**Comment by WhaleHK** [comment]
does it also refresh the cheat? Like in casual when you die you spectate a different team and that disables the cheat. Also new update in CS:GO.
