### ISSUE TITLE
Need a update

### ISSUE THREAD

**Issue by GonZ70** [Blaumaus/le_chiffre#4]
Hi
Don't work anymore need update thx

**Comment by Blaumaus** [comment]
@GonZ70, I've already published the new cheat version, check you the 'releases' tab. 
Star the repository, so you won't miss any future cheat updates.

**Comment by GonZ70** [comment]
Nice :) works fine thx

**Comment by Blaumaus** [comment]
@GonZ70 you are welcome, thanks for the donation
