### ISSUE TITLE
I don't know how to compile pls help

### ISSUE THREAD

**Issue by domen159** [Blaumaus/le_chiffre#40]
Severity	Code	Description	Project	File	Line	Suppression State
Error	C2589	'(': illegal token on right side of '::'	Le_Chiffre	C:\Users\domen\OneDrive\Desktop\CSHax\le_chiffre-main\Le_Chiffre\bsp_parser\valve-bsp-parser\core\matrix.hpp	11	

I used C++17

**Comment by Blaumaus** [comment]
This is a known issue, I'll add FAQs related to this issues into the README soon

**Comment by Blaumaus** [comment]
https://github.com/Blaumaus/le_chiffre#building-the-cheat-yourself
