### ISSUE TITLE
Might be detected..

### ISSUE THREAD

**Issue by WhaleHK** [Blaumaus/le_chiffre#41]
Valve just added a shit load of signatures to their db recently..

Lots of the free cheats/ legit cheats are being detected and this might as well.

Eyez, Clem, & Annihilation are detected as of today and it's really risky atm to use yours. I'm not really sure about this atm, but it's too risky to use any free cheats.

Like the other post about compiling, I would love a tutorial on how to do it so I don't have to rely on the public ver of your cheat. Let's pray Valve hasn't detected this yet..

**Comment by papst0** [comment]
LoL code your own cheat then, how can it be detected if you compile it yourself?

**Comment by WhaleHK** [comment]
> LoL code your own cheat then, how can it be detected if you compile it yourself?

that's why I asked for a tutorial? Maybe read the full post next time.

**Comment by Blaumaus** [comment]
@WhaleHK https://github.com/Blaumaus/le_chiffre#building-the-cheat-yourself
