### ISSUE TITLE
New issue

### ISSUE THREAD

**Issue by KryptoOnn** [Blaumaus/le_chiffre#43]
Just keeps saying Connected to last active game waiting even tho im in game

**Comment by senseless1337** [comment]
New version needed bro

**Comment by KryptoOnn** [comment]
> New version needed bro

what do u mean?

**Comment by M3351AN** [comment]
me toooooo

**Comment by M3351AN** [comment]
OK, now copy hazedumper and paster into signatures.cpp

**Comment by matdu57** [comment]
Hello, i'm ok for modify signature.cpp but how create .exe ? i'have a error with compiler....

**Comment by Blaumaus** [comment]
@M3351AN @KryptoOnn https://github.com/Blaumaus/le_chiffre/releases/tag/v1.3.9
