### ISSUE TITLE
Connected to active game: NO

### ISSUE THREAD

**Issue by xSanx** [Blaumaus/le_chiffre#45]
what's wrong?
![Снимок](https://user-images.githubusercontent.com/46198990/120879354-5cbf3580-c5cb-11eb-8150-6d0faa6ff64f.JPG)

**Comment by matdu57** [comment]
CS have an update and Le_Chiffre not.

**Comment by Blaumaus** [comment]
@xSanx @matdu57 https://github.com/Blaumaus/le_chiffre/releases/tag/v1.3.9
