### ISSUE TITLE
Does not detect Active Game

### ISSUE THREAD

**Issue by Steve4u** [Blaumaus/le_chiffre#56]
I'm connected to the active game, and the cheat does not detect it. 
I also updated it hazedumper, and did not work
![Screenshot_1](https://user-images.githubusercontent.com/92382440/140553564-9771b842-4c0d-4491-8995-20f3ea58d7c0.png)
.

**Comment by Blaumaus** [comment]
https://github.com/Blaumaus/le_chiffre/releases/tag/v1.4.10
