### ISSUE TITLE
How do i get to run the cheat?

### ISSUE THREAD

**Issue by oscargroenberg** [Blaumaus/le_chiffre#6]
Hi
just took a look at your code, and it looks amazing, buuuut, i cant seem to find out how to actually turn on the cheat.
Can you please help?

Thank You
Oscar

**Comment by Blaumaus** [comment]
@oscargroenberg compile the code or download a precompiled app from 'Releases' section -> Run the .exe file -> Select needed features (by pressing F2-F9 buttons) -> Profit!

**Comment by daniel11609** [comment]
Hey Blaumaus,

i tried to compile your program, but I failed :(
Which compiler is neccessary / which command do I have to use to compile the cheat? I only get error when I try to use "g++" from MingW.

Your help is appreciated
