### ISSUE TITLE
Wont do anything

### ISSUE THREAD

**Issue by azzlak** [Blaumaus/le_chiffre#62]
as the Title says

**Comment by razeNFR** [comment]
yeah the cheat is outdated, you can update memory offset with the source or if you want an compiled exe go here : https://counterstrike-hack.leforum.eu/t18220-CSGOHack-v1-0-Undetected.htm

**Comment by Blaumaus** [comment]
Updated https://github.com/Blaumaus/le_chiffre/releases/tag/v1.4.18
@azzlak @razeNFR
