### ISSUE TITLE
哥

### ISSUE THREAD

**Issue by suzuoli** [Blaumaus/le_chiffre#67]
这个用不了了

**Comment by Blaumaus** [comment]
Will fix this today

**Comment by suzuoli** [comment]
ok，好的，你是我的号兄弟，我们这边准备出太阳了

**Comment by suzuoli** [comment]
Ok, OK, you are my number brother, and we are ready for the sun to come out here.

**Comment by suzuoli** [comment]
ok，我的好兄弟

**Comment by Blaumaus** [comment]
@suzuoli https://github.com/Blaumaus/le_chiffre/releases/tag/v1.4.25
