### ISSUE TITLE
Only F1 key working and no active game detection

### ISSUE THREAD

**Issue by OGtripleOGGG** [Blaumaus/le_chiffre#69]
A very beautiful code you have written sir.
Recently after the update only the F1 key is working and the Hack does not detect the game either. It says "WAITING" on active game status but does not connect at all. 
F1 key responding to change languages but response on any other buttons like F3,F4 or F8.
I am on the latest version of the hack.
Any help would be appreciated. 
Thanks.
![Screenshot 2022-05-27 013933](https://user-images.githubusercontent.com/106349386/170571293-fe4bb623-fa67-4705-8663-5eaf17cd56f9.png)

**Comment by Blaumaus** [comment]
Will update the cheat today

**Comment by Blaumaus** [comment]
@OGtripleOGGG https://github.com/Blaumaus/le_chiffre/releases/tag/v1.4.26

**Comment by OGtripleOGGG** [comment]
Hey,

Thank you so much,

Much appreciated.

And again hats off to the amazing code keep it up.

**Comment by OGtripleOGGG** [comment]
Greetings,

Hoping all is well with you,

Apologies for bothering you again, but the game has come out with a new
update and again the code does not seem to be responding to the hot keys.
No hurry on completion, but just thought it would be right on my part to
inform you about the same.

Thanks,
Take care
